### ISSUE TITLE
demo运行时不报错，但显示不了图表

### ISSUE THREAD

**Issue by fed2019** [pyecharts/pyecharts-gallery#10]
您好，pyecharts-gallery 中的demo运行时都不报错，但是显示不了图表，请问这是什么原因？
pyecharts 版本1.6.0
python 3.7
IDE: Pycharm

**Comment by sunhailin-Leo** [comment]
@fed2019 
1、请具体指出是哪个 demo.
2、请给出一下 html 控制台的日志

**Comment by fed2019** [comment]
1.air_quality_baidu_map.html可以用浏览器打开并显示图表，air_quality_baidu_map.py程序运行时显示不了图表。
2.air_quality_baidu_map.py运行时控制台日志如下：
F:\python\python.exe G:/python_work/GUI_project/pyecharts-gallery-master/Geo_Map_BMap/air_quality_baidu_map.py

Process finished with exit code 0

谢谢！

**Comment by sunhailin-Leo** [comment]
@fed2019 
* 我这边本地测试没有问题
* 我说的控制台不是 Pycharm 的，是浏览器的

**Comment by fed2019** [comment]
已经解决了，是我自己理解有问题，谢谢解答。
