### ISSUE TITLE
pyecharts 用grid拼接两幅图，每幅图都有一个划块，拼接后只显示一个滑块

### ISSUE THREAD

**Issue by 3165523246** [pyecharts/pyecharts-gallery#101]
[isuss.zip](https://github.com/pyecharts/pyecharts-gallery/files/13427132/isuss.zip)

#  因为grid拼接生产的html只有一个id，然后一个id只能显示一个组件，ehcarts前端代码可以手动控制，pyecharts的grid无法控制拼接多张图有多个组件的问题。

**Comment by sunhailin-Leo** [comment]
@3165523246 
* 贴一下截图和代码吧，zip 包不方便打开

**Comment by 3165523246** [comment]
@sunhailin-Leo   
![image](https://github.com/pyecharts/pyecharts-gallery/assets/116544481/5cc3cf35-0d25-491e-8ebd-ff5d8f18033c)
![image](https://github.com/pyecharts/pyecharts-gallery/assets/116544481/b122e586-ca30-4a84-b05f-29ddefd414af)
![image](https://github.com/pyecharts/pyecharts-gallery/assets/116544481/c6f60573-ea02-46f5-915f-dcd2341f3722)
![image](https://github.com/pyecharts/pyecharts-gallery/assets/116544481/f6e2a7a3-d56a-4e9c-96f1-5ad14d27f37b)
最后一张是grid4.html  ，我研究啦一下，重写grid父类的render方法应改可以解决，但我没写出来

**Comment by 3165523246** [comment]
@sunhailin-Leo   想实现方法很多，但这是一个bug，应该解决它

**Comment by sunhailin-Leo** [comment]
@3165523246 
* 提个 issue 去 main repo 吧。

**Comment by sunhailin-Leo** [comment]
@3165523246 
![image](https://github.com/pyecharts/pyecharts-gallery/assets/17564655/ea319fbe-f10c-4482-8d30-357cebbcfb6e)

**Comment by 3165523246** [comment]
@sunhailin-Leo  这是解决啦吧 可以看看代码吗

**Comment by sunhailin-Leo** [comment]
@3165523246 
* 这个只是我临时改的哈～
* 等下个版本发版后才能够展示多个 datazoom 的配置。
* 而且这里面 grid 的 datazoom 也需要调整位置的，并不能自适应位置。原因是 echarts 把图和 datazoom 分离渲染的
