### ISSUE TITLE
overlap怎么设置透明度？

### ISSUE THREAD

**Issue by cjztool** [pyecharts/pyecharts-gallery#103]
<img width="902" alt="image" src="https://github.com/pyecharts/pyecharts-gallery/assets/3993323/ec162838-46e6-4dca-9fa7-a8f4025ee42c">
请教下 图中  折线  被  bar  遮挡了，怎么解决

**Comment by sunhailin-Leo** [comment]
@cjztool 
* 这个不是设置透明度哈~而是设置 z 或者 zlevel 的层级

**Comment by cjztool** [comment]
谢谢指导
