### ISSUE TITLE
is it possible to draw a gantt graph using pyecharts？

### ISSUE THREAD

**Issue by madainigun14** [pyecharts/pyecharts-gallery#106]
According to the Apache echarts examples: https://echarts.apache.org/examples/en/editor.html?c=custom-gantt-flight
is it possible to draw a gantt graph using pyecharts？

**Comment by sunhailin-Leo** [comment]
@madainigun14 
* I think it is very difficult to use pyecharts to implement it. Because that example use a lot of js functions and logics to draw it.
