### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 182: illegal multibyte sequence 报错

### ISSUE THREAD

**Issue by xianjunhong** [pyecharts/pyecharts-gallery#108]
![image](https://github.com/user-attachments/assets/84eb0843-c365-41a2-99fa-0946789d245c)

**Comment by sunhailin-Leo** [comment]
@xianjunhong 
* 这个脚本不是这么用的。
* 这个项目目前没有提供出来可以运行的脚本哈
