### ISSUE TITLE
全局配置项 TooltipOpts 参数问题

### ISSUE THREAD

**Issue by fed2019** [pyecharts/pyecharts-gallery#11]
以下是formatter 参数的配置方法的说明文档：

# 标签内容格式器，支持字符串模板和回调函数两种形式，字符串模板与回调函数返回的字符串均支持用 \n 换行。
    # 字符串模板 模板变量有：
    # {a}：系列名。
    # {b}：数据名。
    # {c}：数据值。
    # {@xxx}：数据中名为 'xxx' 的维度的值，如 {@product} 表示名为 'product'` 的维度的值。
    # {@[n]}：数据中维度 n 的值，如{@[3]}` 表示维度 3 的值，从 0 开始计数。
    # 示例：formatter: '{b}: {@score}'

问题： {@xxx} {@[n]} 这两项不知道如何使用！求解答。

**Comment by sunhailin-Leo** [comment]
@fed2019 
* 实在看不懂的，写 JsCode，用 js 代码回调
