### ISSUE TITLE
Line，多根线显示时候问题

### ISSUE THREAD

**Issue by liuyannnnn** [pyecharts/pyecharts-gallery#110]
![image](https://github.com/user-attachments/assets/a9081fde-1c3b-4f71-a9ac-e2348a604f5a)
![image](https://github.com/user-attachments/assets/fc42e577-a17a-4aa2-a1c4-9545df8b8200)
如果X轴数据较少，显示比较正常，数据稍多后就错乱了，数值小的还跑数值大的上面去了

**Comment by sunhailin-Leo** [comment]
@liuyannnnn 
* 去主仓库提哈～
