### ISSUE TITLE
grid中添加了两个PIP饼图，饼图的标签不能显示完

### ISSUE THREAD

**Issue by hurricane1988** [pyecharts/pyecharts-gallery#16]
![image](https://user-images.githubusercontent.com/16606960/78653895-5b767800-78f6-11ea-8570-ffc3504a38e2.png)

osVersionPip = (
    Pie()
    .add(
        "",
        osVersion(),
        radius=["55", "40%"],
        center=["38%", "28%"],
        label_opts=opts.LabelOpts(
            position="outside",
            #formatter="{a|{a}}{abg|}\n{hr|}\n {b|{b}: }{c}  {per|{d}%}  ",
            formatter="{hr|}\n {b|{b}: }{c}  {per|{d}%}  ",
            background_color="#eee",
            border_color="#aaa",
            border_width=1,
            border_radius=5,
            rich={
                #"a": {"color": "#999", "lineHeight": 5, "align": "center"},
                "abg": {
                    "backgroundColor": "#e3e3e3",
                    "width": "100%",
                    "align": "right",
                    "height": 22,
                    "borderRadius": [4, 4, 0, 0],
                },
                "hr": {
                    "borderColor": "#aaa",
                    "width": "100%",
                    "borderWidth": 1,
                    "height": 0,
                },
                "b": {"fontSize": 11, "lineHeight": 25},
                "per": {
                    "color": "#eee",
                    "backgroundColor": "#334455",
                    "padding": [2, 4],
                    "borderRadius": 2,
                },
            },
        ),
    )
    #.set_global_opts(title_opts=opts.TitleOpts(title="操作系统版本信息"))
    .set_global_opts(
        #title_opts=opts.TitleOpts(title="Pie-Legend 滚动"),
        legend_opts=opts.LegendOpts(type_="scroll",  pos_left="85%",orient="vertical"),
    )
    #.render("./templates/osVersionPip.html")
)

osTypePip = (
    Pie()
    .add(
        "",
        osType(),
        radius=["55", "40%"],
        center=["38%", "80%"],
        label_opts=opts.LabelOpts(
            position="outside",
            #formatter="{a|{a}}{abg|}\n{hr|}\n {b|{b}: }{c}  {per|{d}%}  ",
            formatter="{hr|}\n {b|{b}: }{c}  {per|{d}%}  ",
            background_color="#eee",
            border_color="#aaa",
            border_width=1,
            border_radius=5,
            rich={
                #"a": {"color": "#999", "lineHeight": 5, "align": "center"},
                "abg": {
                    "backgroundColor": "#e3e3e3",
                    "width": "100%",
                    "align": "right",
                    "height": 22,
                    "borderRadius": [4, 4, 0, 0],
                },
                "hr": {
                    "borderColor": "#aaa",
                    "width": "100%",
                    "borderWidth": 1,
                    "height": 0,
                },
                "b": {"fontSize": 11, "lineHeight": 25},
                "per": {
                    "color": "#eee",
                    "backgroundColor": "#334455",
                    "padding": [2, 4],
                    "borderRadius": 2,
                },
            },
        ),
    )
    #.set_global_opts(title_opts=opts.TitleOpts(title="操作系统版本信息"))
    .set_global_opts(
        #title_opts=opts.TitleOpts(title="Pie-Legend 滚动"),
        legend_opts=opts.LegendOpts(type_="scroll", pos_top="55%" ,pos_left="85%",orient="vertical",is_show=True),
    )
    #.render("./templates/osVersionPip.html")
)

grid = (
    Grid()
    .add(osTypePip,grid_opts=opts.GridOpts(pos_bottom="60%"))
    .add(osVersionPip, grid_opts=opts.GridOpts(pos_top="60%"))
    .render("./templates/grid_horizontal.html")
)

**Comment by chenjiandongx** [comment]
@hurricane1988 请把问题发到 [pyecharts](https://github.com/pyecharts/pyecharts) 主项目 issue 专区
