### ISSUE TITLE
jupyter notebook 中若将 bar.render_notebook() 置于函数内则图像不显示

### ISSUE THREAD

**Issue by WenyinWei** [pyecharts/pyecharts-gallery#20]
如题，render_notebook() 似乎只有在全局域时图像才会出现。

**Comment by WenyinWei** [comment]
另外似乎对于 3D 图，timeline 时间轴无法使用，render() 会生成空白 html 或 render_notebook() 在 notebook 内产生空白。

**Comment by sunhailin-Leo** [comment]
@WenyinWei 
* render 方法需要图像的对象才可以调用
* timeline 也没说支持 3D 图
