### ISSUE TITLE
如何在K线图浮窗中显示涨跌幅？

### ISSUE THREAD

**Issue by RangerinDarkWoods** [pyecharts/pyecharts-gallery#23]
目前的几种K线图仅支持显示开盘收盘最低最高等信息，那么如何显示本期相对于上期的涨跌幅呢？是否需要添加序列，但显得没有必要。如图所示：
![image](https://user-images.githubusercontent.com/65518441/84727802-73d3d480-afc2-11ea-9454-8d918a7030e0.png)

**Comment by sunhailin-Leo** [comment]
@RangerinDarkWoods 
* 这个功能不属于 `pyecharts` 的考虑范畴
