### ISSUE TITLE
图像的位置

### ISSUE THREAD

**Issue by kerwinxu** [pyecharts/pyecharts-gallery#42]
https://pyecharts.org/#/zh-cn/global_options
这个图上有各个元素的设置，但好像唯独没有中间图形的设置，因为我的图例项目太多，跟图形有重叠，所以我设置图例配置项在整个图形的右边，不过依然有重叠，我想将中间的图形再向左一些，但却没有中间图形的配置项目，更没有pos_left了。请问怎么解决。

**Comment by sunhailin-Leo** [comment]
@kerwinxu 
* 1、画布放大些
* 2、图例可以用滚动布局
* 3、Grid
