### ISSUE TITLE
Map绘图中的数据是否可以用对数表示？

### ISSUE THREAD

**Issue by Cyan010320** [pyecharts/pyecharts-gallery#48]
图例默认把数据均等划分，导致地图变成了这样，是否可以改为对数表示？将opts.AxisOpts中的type_改为'log'似乎并不起作用。
<img width="910" alt="截屏2021-01-29 上午10 20 34" src="https://user-images.githubusercontent.com/51875984/106223022-a235b580-621b-11eb-9904-7d024958b883.png">

**Comment by sunhailin-Leo** [comment]
@Cyan010320 
* 目前还是头一次见到在 Geo/Map 的数据中用对数展示。如果可以的话，建议先通过 math 库或者 numpy 处理好之后，使用原生数据类型进行展示。
