### ISSUE TITLE
树图Tree的示例能否像echarts的官方示例一样展开第3层之后的节点？

### ISSUE THREAD

**Issue by xubosong** [pyecharts/pyecharts-gallery#5]
**问题描述**
我在使用pyecharts绘制树图的过程中，发现pyecharts绘制出的树图默认只展开0, 1, 2这三层节点，后面更深层的节点是折叠起来的。我希望绘制出的树图初始就能展开所有层级的节点，不要隐藏。

在echarts中有2个参数可以实现这个功能，设置参数initialTreeDepth: -1或者expandAndCollapse: false都可以使各层节点全部展开（见截图）。但pyecharts似乎没有对应的参数。
![BaiduShurufa_2019-8-29_20-7-56](https://user-images.githubusercontent.com/50367222/63939019-cd512e00-ca98-11e9-92e6-719280016b74.png)

**示例**
我运行了您给出的echarts官方示例树图的python代码
https://github.com/pyecharts/pyecharts-gallery/blob/master/Tree/radial_tree.py
也存在不能默认展开多层节点的问题，但您的代码注释中并未说明无法实现此功能。
![image](https://user-images.githubusercontent.com/50367222/63939211-4b153980-ca99-11e9-8a76-57c6f007772c.png)

echarts官方示例树图
https://echarts.baidu.com/examples/editor.html?c=tree-radial
截图中红框标注部分的参数并没有在您的python代码中体现。这里能否向您请教如何修改程序，使之与echarts相对应，可以通过参数控制默认的树图展开层数？
![BaiduShurufa_2019-8-29_20-20-55](https://user-images.githubusercontent.com/50367222/63939743-8ebc7300-ca9a-11e9-9965-9dc3ef6c56f8.png)

我想可能需要修改pyecharts这个module的一些程序才能解决，但我还没有找到修改的方法。

**Comment by sunhailin-Leo** [comment]
@xubosong `pyecharts` 新版本中会加入该配置，Is coming soon...
