### ISSUE TITLE
新版datazoom只支持1个？

### ISSUE THREAD

**Issue by flyxiti** [pyecharts/pyecharts-gallery#50]
目前没有办法同时设置横轴和纵轴的zoom。请指教。

**Comment by sunhailin-Leo** [comment]
@flyxiti 
* `datazoom_opts` 支持列表格式。因此它支持多个

**Comment by flyxiti** [comment]
> 
> 
> @flyxiti
> 
>     * `datazoom_opts` 支持列表格式。因此它支持多个

直接修改html确实是实现了多个datazoom的，但是在定义opts.DataZoomOpts的orient时只能定义vertical或horizontal，想要生成多个datazoom未能成功。望指教。
