### ISSUE TITLE
建议示例中提供完整的代码

### ISSUE THREAD

**Issue by lyl1836** [pyecharts/pyecharts-gallery#52]
许多开源项目，示例代码是可以直接拷过来就能演示，这样也容易提升使用者的兴趣。

pyecharts 的示例代码，不知为什么运行不起来。

**Comment by sunhailin-Leo** [comment]
@lyl1836 
* 请描述具体一些

**Comment by sunhailin-Leo** [comment]
@lyl1836 
* 运行不起来的原因有很多，有的时候不应该和代码有关。即使 Echarts 贴了完整的示例代码，也会有无法运行的情况。
* 因此，如果有运行不起来的代码，可以提 issue，谢谢。
