### ISSUE TITLE
进度条什么时候加上

### ISSUE THREAD

**Issue by lice-coder** [pyecharts/pyecharts-gallery#54]

**Comment by sunhailin-Leo** [comment]
@lice-coder 
* 什么进度条？

**Comment by lice-coder** [comment]
> _No description provided._
![image](https://user-images.githubusercontent.com/60214334/113649521-28112980-96c1-11eb-9fc0-ee8524c71e1d.png)
类似这种的

**Comment by sunhailin-Leo** [comment]
@lice-coder 
* Show full example.

**Comment by lice-coder** [comment]
![image](https://user-images.githubusercontent.com/60214334/113649736-89d19380-96c1-11eb-90b5-4ec1b42f258b.png)

**Comment by lice-coder** [comment]
![image](https://user-images.githubusercontent.com/60214334/113649833-bbe2f580-96c1-11eb-8c85-b7de0a1e85fb.png)
想实现Echarts的这种效果~

**Comment by lice-coder** [comment]
我现在只能用堆叠柱状图去模拟一个了
