### ISSUE TITLE
颜色显示反了

### ISSUE THREAD

**Issue by ppobber** [pyecharts/pyecharts-gallery#55]
![屏幕截图 2021-04-17 161825](https://user-images.githubusercontent.com/34465000/115106675-be363100-9f98-11eb-8459-f45f02de2aec.png)
### ### 
一条条添加y数据，指定的颜色对不上，显示反了。

**Comment by sunhailin-Leo** [comment]
@ppobber 
* 目前 dev 分支已经解决了，后续发布 2.0 版本的时候就好了
