### ISSUE TITLE
How to plot binning on map using pyecharts?

### ISSUE THREAD

**Issue by xushaozhi** [pyecharts/pyecharts-gallery#6]
Echarts Demo
https://www.echartsjs.com/examples/zh/editor.html?c=map-bin

**Comment by sunhailin-Leo** [comment]
@xushaozhi little hard to implement, but I will try it after work.

**Comment by sunhailin-Leo** [comment]
@xushaozhi 
* This map I can draw it now~, but developer need to wait for the next version (1.6.2).
