### ISSUE TITLE
分省地图中的省名可否尽量放在省域的中间？字体的大小可以设置吗？

### ISSUE THREAD

**Issue by A-Pai** [pyecharts/pyecharts-gallery#63]
分省地图中的省名可否尽量放在省域的中间？字体的大小可以设置吗？
例如下图中箭头所指的：
![image](https://user-images.githubusercontent.com/5112397/128600786-7f96ffc7-8d76-4a6b-9713-b63ca0ed61cd.png)

**Comment by sunhailin-Leo** [comment]
@A-Pai 
* 这个暂时无法设置
