### ISSUE TITLE
Grid与yaxis_index冲突的问题

### ISSUE THREAD

**Issue by jidalhl** [pyecharts/pyecharts-gallery#65]
在没有grid的图表中，创建1个Line（），并使用extend_axis方法在右侧新增添Y轴，在add_yaxis中使用yaxis_index=1属性绑定Y轴，图表数据可以正常关联右侧新增添的Y轴。
当我把这个Line，放到Grid中时，原先关联右侧新增添的数据就会自动关联左侧的Y轴，而不是右侧的Y轴

**Comment by LintianShi** [comment]
我也遇到了这个问题，请问您后面是如何解决的？

**Comment by yanghe4405** [comment]
同样的问题，求解啊~~~
