### ISSUE TITLE
custom_background_image  这个示例好像有问题 背景图片是偏移的

### ISSUE THREAD

**Issue by Harris-H** [pyecharts/pyecharts-gallery#67]
![image](https://user-images.githubusercontent.com/57698783/139463781-e4f0f471-714f-4b06-a806-b6340eeb04de.png)

是我的浏览器问题吗？还是代码的设置有问题？

**Comment by sunhailin-Leo** [comment]
@Harris-H 
* 用 js 给图片设置下平铺就好了。gallery 只是示例
