### ISSUE TITLE
scatter散点图如何展示分类数据

### ISSUE THREAD

**Issue by gsy44355** [pyecharts/pyecharts-gallery#68]
有两类数据，类别1共五个
<pre>
[[11.56023120880127, 27.040817260742188],
 [-5.224257469177246, -15.477859497070312],
 [-19.645002365112305, -15.719226837158203],
 [25.8948917388916, 5.323724746704102],
 [-15.496088027954102, 23.81446647644043]]
</pre>
类别2共10个
<pre>
[[-4.203354835510254, -23.947246551513672],
 [-9.199494361877441, 19.46872901916504],
 [-3.9750850200653076, 17.684152603149414],
 [10.8388032913208, 15.954113006591797],
 [-9.237049102783203, 19.43368911743164],
 [19.628984451293945, 18.176530838012695],
 [-22.891176223754883, 7.592852592468262],
 [-17.271387100219727, -8.168133735656738],
 [-3.8871994018554688, 17.787797927856445],
 [10.617372512817383, 15.911705017089844]]
</pre>
我应该如何正确的将这些数据展示在同一个散点图中并区分不同的颜色？我尝试了如下代码，但是没有得到正确的显示
```
from pyecharts import options as opts
from pyecharts.charts import Scatter
from pyecharts.faker import Faker

c = (
    Scatter()
    .add_xaxis(x1)
    .add_yaxis("black", y1)
    .add_xaxis(x2)
    .add_yaxis("white",y2)
    .set_global_opts(title_opts=opts.TitleOpts(title="EffectScatter-基本示例"))
    .render("effectscatter_base.html")
)
```

**Comment by 1570709908** [comment]
请问最后解决了吗？我也遇到了类似的问题，想请教一下
