### ISSUE TITLE
是否可以在中国的城市层面地图上加上九段线和南海诸岛小地图，谢谢！

### ISSUE THREAD

**Issue by StefanFyy** [pyecharts/pyecharts-gallery#71]
pyecharts的地图真的是非常棒了，中国地市级的地图也很好，但和省级的比缺少了九段线和南海诸岛，如果用在报告或者文章里，可能会被点名。所以能否麻烦大大加上，感激不尽！

**Comment by sunhailin-Leo** [comment]
@StefanFyy 
* 自行修改 echarts 的 map json 文件
