### ISSUE TITLE
Bar 中某一类数据长度过长导致图中不显示的问题

### ISSUE THREAD

**Issue by LZhangGJ** [pyecharts/pyecharts-gallery#74]
e.g

list1 = [{'value': 31.0, 'percent': 0.3333333333333333},
 {'value': 26.0, 'percent': 0.27956989247311825},
 {'value': 21.0, 'percent': 0.22580645161290322},
 {'value': 15.0, 'percent': 0.16129032258064516},
 {'value': 18.0, 'percent': 0.1935483870967742},
 {'value': 18.0, 'percent': 0.1935483870967742},
 {'value': 42.0, 'percent': 0.45161290322580644},
 {'value': 17.0, 'percent': 0.1827956989247312},
 {'value': 6.0, 'percent': 0.06451612903225806},
 {'value': 4.0, 'percent': 0.043010752688172046},
 {'value': 7.0, 'percent': 0.07526881720430108},
 {'value': 18.0, 'percent': 0.1935483870967742},
 {'value': 93, 'percent': 1.0},
 {'value': 14.0, 'percent': 0.15053763440860216},
 {'value': 5.0, 'percent': 0.053763440860215055},
 {'value': 10.0, 'percent': 0.10752688172043011},
 {'value': 8.0, 'percent': 0.08602150537634409},
 {'value': 11.0, 'percent': 0.11827956989247312},
 {'value': 3.0, 'percent': 0.03225806451612903}]

c = (
    Bar(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
    .add_xaxis(list(range(19)))
    .add_yaxis(r"", d, category_gap="50%")
    .set_series_opts(
        label_opts=opts.LabelOpts(
            position="right",
            formatter=JsCode(
                "function(x){return Number(x.data.percent * 99.99999).toFixed() + '%';}"
            )
        )
        
    )
    .set_global_opts(
        xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=-50)),
        title_opts=opts.TitleOpts(title=" "),
    )
)
c.render_notebook()

其中第12类由于样本过多显示空白
望解答，万分感谢

**Comment by sunhailin-Leo** [comment]
@LZhangGJ 
* 请格式化代码，并贴上图例
