### ISSUE TITLE
实时更新k线数据的问题

### ISSUE THREAD

**Issue by platinum9999** [pyecharts/pyecharts-gallery#77]
有什么办法可以绘制实时更新的k线图表吗？
我的想法是 已获取到股市实tick 数据（开高低收等），如何绘制实时跳动的k线图？
我的要求是通过这些数据 按照我自己的想法去作图，比如我想画实时更新价格的砖型图，xo图等！
我看了许多案例，基本上都是千篇一律的将数据提取出来再作图，最后保存为html页面，这个保存之后的页面数据对于需要实时接收数据的这种情况也就失去了实质性的意义，
请问，有什么办法可以实现吗？

**Comment by sunhailin-Leo** [comment]
@platinum9999 
* 可以参考：https://pyecharts.org/#/zh-cn/web_flask?id=%e5%ae%9a%e6%97%b6%e5%a2%9e%e9%87%8f%e6%9b%b4%e6%96%b0%e5%9b%be%e8%a1%a8
