### ISSUE TITLE
How to plot npm_dependencies(关系图) on geomap and Bmap?

### ISSUE THREAD

**Issue by xushaozhi** [pyecharts/pyecharts-gallery#8]
https://github.com/pyecharts/pyecharts-gallery/blob/master/Graph/npm_dependencies.py
API里面graph的coordinateSystem可以设置成‘geo’，请问该用什么形式传值，能否提供个Demo？感谢！

**Comment by chenjiandongx** [comment]
有问题请到 https://github.com/pyecharts/pyecharts/issues 提问
