### ISSUE TITLE
可以完善page中适配tabs的功能吗

### ISSUE THREAD

**Issue by Jasonjk3** [pyecharts/pyecharts-gallery#84]
如题，现在tabs与page并不兼容，对于多个相同类型的图表不能放在同一个tabs里对整个dashborad的布局不是很友好。还有能不能增加一些全局或局部的过滤筛选器，选择框之类的？

**Comment by sunhailin-Leo** [comment]
@Jasonjk3 
* 这个属于前端的功能需求了，不符合 pyecharts 的设计
