### ISSUE TITLE
地图不显示颜色

### ISSUE THREAD

**Issue by sunnysheng** [pyecharts/pyecharts-gallery#86]
提供的map example的代码，执行后地图是灰的，不显示颜色。

**Comment by sunhailin-Leo** [comment]
@sunnysheng 
* 更新下 2.0.1 
* pyecharts 的 issue 已经有说明：https://github.com/pyecharts/pyecharts/issues/2107

**Comment by Kaneyu8891** [comment]
额，同样的问题，我更新了pyecharts2.0.1，用样例代码和我自己的代码都不显示颜色。
https://gallery.pyecharts.org/#/Map/map_base
文档里的图也是灰色无数据的样子。
