### ISSUE TITLE
MAP的地图API好像挂了

### ISSUE THREAD

**Issue by afrunk** [pyecharts/pyecharts-gallery#88]
官网的地图也无法显示数据了，https://gallery.pyecharts.org/#/Map/map_base。本地生产的HTML也无法正常显示，是地图的API挂掉了嘛？

**Comment by sunhailin-Leo** [comment]
@afrunk 
* 你自己的网络问题吧?🤔
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/17564655/223099739-8c5e60bb-94d5-4028-9ed0-2717c8a40bee.png">
