### ISSUE TITLE
highlight on hover

### ISSUE THREAD

**Issue by josepaulo1233** [pyecharts/pyecharts-gallery#95]
Hi, there's a way to highlight the line when hover? Like this example: https://echarts.apache.org/examples/en/editor.html?c=line-race

**Comment by buhbuhtig** [comment]
I've got the same question! It's called "emphasis" in echarts, but  I've found no trace of its implementation in the pyecharts.

**Comment by sunhailin-Leo** [comment]
https://github.com/pyecharts/pyecharts/issues/2263
