### ISSUE TITLE
Running all examples will delete some files in the virtual environment

### ISSUE THREAD

**Issue by Alan3344** [pyecharts/pyecharts-gallery#97]
Platform: Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin

Error: subprocess.CalledProcessError: Command '['python3', 'tree_base.py']' returned non-zero exit status 1.
- 使用脚本创建虚拟环境

![image](https://github.com/pyecharts/pyecharts-gallery/assets/60773912/ea7f04f9-b9e9-4838-b91d-8416749dcae8)
![image](https://github.com/pyecharts/pyecharts-gallery/assets/60773912/bb22d678-fe94-47d1-a01c-991cc59a2be3)

运行之后env部分文件就被删除了
- pip也被删除了
![image](https://github.com/pyecharts/pyecharts-gallery/assets/60773912/4790ee3a-351d-44a9-af64-8a1e571e6159)

![image](https://github.com/pyecharts/pyecharts-gallery/assets/60773912/eec98cdb-e49f-474d-9a04-247b43779b74)

![image](https://github.com/pyecharts/pyecharts-gallery/assets/60773912/905f9b1e-2572-4e28-8e1d-14ce2a549394)

**Comment by sunhailin-Leo** [comment]
@Alan3344 
* emm 这个。。因为我个人不是很喜欢用虚拟环境这种东西，所以没测试过~

**Comment by Alan3344** [comment]
> @Alan3344
> 
> * emm 这个。。因为我个人不是很喜欢用虚拟环境这种东西，所以没测试过~

这个初始化删除文件有点狠，好在不是什么重要文件，我只是想clone下来跑下，没想到会这样
我以前也不用，直到遇到了：不同的项目依赖同样的包的不同版本，最后查到是包版本才开始用的虚拟环境

**Comment by sunhailin-Leo** [comment]
> > @Alan3344
> > 
> > * emm 这个。。因为我个人不是很喜欢用虚拟环境这种东西，所以没测试过~
> 
> 这个初始化删除文件有点狠，好在不是什么重要文件，我只是想clone下来跑下，没想到会这样 我以前也不用，直到遇到了：不同的项目依赖同样的包的不同版本，最后查到是包版本才开始用的虚拟环境

* 因为当时写那个脚本只考虑到这个项目，所以删东西没想那么多
